import { Card,StatusBadge } from "@policylens/ui";
import {
Bot,
Check,
CircleAlert,
FileSearch,
Info,
Scale,
ShieldCheck,
Sparkles
} from "lucide-react";
import { useEffect,useState } from "react";
import { policyLens } from "../../api";
import { asError,ErrorPanel,fieldLabels,KeyRow,money,PageHeader } from '../../components/layout/LegacyShared';
import type { AnalysisView,EvidenceComparisonView,PreviewSelectionView,PreviewView,ProductDetail,ProductSummary } from '../research/types';
export function ComparisonPage({ openProduct, initialIds = [], fixedSelection = false }: { openProduct: (id: string) => void; initialIds?: string[]; fixedSelection?: boolean }) {
  const [products, setProducts] = useState<ProductSummary[]>([]);
  const [selected, setSelected] = useState<string[]>(initialIds);
  const [comparison, setComparison] = useState<{ products: ProductDetail[]; notice: string } | null>(null);
  const [evidenceComparison, setEvidenceComparison] = useState<EvidenceComparisonView | null>(null);
  const [preview, setPreview] = useState<PreviewView | null>(null);
  const [previewSelection, setPreviewSelection] = useState<PreviewSelectionView | null>(null);
  const [selectedEvidence, setSelectedEvidence] = useState<string[]>([]);
  const [confirmed, setConfirmed] = useState(false);
  const [previewUsed, setPreviewUsed] = useState(false);
  const [analysis, setAnalysis] = useState<AnalysisView | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  useEffect(() => { policyLens.listProducts(false).then((value) => setProducts(value as ProductSummary[])).catch((reason) => setError(asError(reason))); }, []);
  const toggle = (id: string) => { if(busy || fixedSelection) return; setSelected(current => current.includes(id) ? current.filter(item => item !== id) : current.length < 4 ? [...current,id] : current); setComparison(null);setEvidenceComparison(null);setPreview(null);setPreviewSelection(null);setSelectedEvidence([]);setAnalysis(null);setConfirmed(false); };
  const compare = async () => { setBusy(true); setError(""); try { setEvidenceComparison(await policyLens.compareEvidence(selected) as EvidenceComparisonView); setComparison(selected.length === 2 ? await policyLens.compare(selected) as { products: ProductDetail[]; notice: string } : null); setPreview(null); setAnalysis(null); } catch (reason) { setError(asError(reason)); } finally { setBusy(false); } };
  const makePreview = async (evidenceIds?: string[]) => { setPreviewUsed(false); setBusy(true); setError(""); try { const result = await policyLens.previewCodex(selected, evidenceIds) as PreviewView | PreviewSelectionView; if ("requires_selection" in result) { setPreviewSelection(result); setSelectedEvidence(result.evidence_options.slice(0, 12).map((item) => item.evidenceId)); setPreview(null); } else { setPreview(result); setPreviewSelection(null); } setConfirmed(false); } catch (reason) { setError(asError(reason)); } finally { setBusy(false); } };
  const run = async () => { if (!preview || !confirmed || previewUsed) return; setPreviewUsed(true); setConfirmed(false); setBusy(true); setError(""); try { const executed = await policyLens.runCodex(preview.payload); const evidenceIds = preview.payload.comparison.evidenceExcerpts.map((item) => item.evidenceId); const saved = await policyLens.saveAnalysis({ preview_hash: preview.preview_hash, evidence_ids: evidenceIds, result: executed.result, cli_version: executed.cliVersion, argument_profile: "EPHEMERAL_JSON_READ_ONLY_SCHEMA_V1", prompt_template_version: "policylens-analysis-v1", exit_status: 0, schema_valid: true }); setAnalysis(saved as AnalysisView); } catch (reason) { setError(asError(reason)); } finally { setBusy(false); } };
  const updateStatus = async (status: "ACCEPTED_AS_NOTE" | "REJECTED") => { if (!analysis) return; setAnalysis(await policyLens.updateAnalysisStatus(analysis.id, status) as AnalysisView); };
  return <><PageHeader title="产品证据对比" subtitle="选择 2–4 个已核验版本，按同一字段查看值、状态和证据数量" actions={<button className="button primary" disabled={selected.length < 2 || busy} onClick={() => void compare()}><Scale size={18} />生成证据对比</button>} />{error && <ErrorPanel message={error} />}
    <Card><div className="card-title"><h2>选择 2–4 个版本</h2><span>{selected.length}/4</span></div>{products.length ? <div className="product-picker">{products.map((product) => <button key={product.version_id} className={selected.includes(product.version_id) ? "selected" : ""} disabled={busy || fixedSelection} onClick={() => toggle(product.version_id)}><span className="check-circle">{selected.includes(product.version_id) && <Check />}</span><strong>{product.display_name}</strong><small>{product.version_label} · {product.currency}</small></button>)}</div> : <div className="small-empty"><Scale /><p>还没有两个可比较的已核验版本。请先完成官方候选的逐字段核验。</p></div>}</Card>
    {evidenceComparison && <Card className="evidence-matrix"><div className="card-title"><h2>字段与证据矩阵</h2><StatusBadge tone="info">不排名、不推荐</StatusBadge></div><div className="matrix-scroll"><table><thead><tr><th>字段</th>{evidenceComparison.products.map((product) => <th key={product.version_id}>{product.display_name}<small>{product.version_label}</small></th>)}</tr></thead><tbody>{evidenceComparison.rows.map((row) => <tr key={row.field_path}><td><strong>{fieldLabels[row.field_path] ?? row.field_path}</strong></td>{row.cells.map((cell) => <td key={cell.version_id}><strong>{cell.value ?? "未知"} {cell.unit ?? ""}</strong><small>{cell.verification_status} · {cell.guarantee_type}</small><small>{cell.evidence_count} 条证据{cell.evidence_ids.length ? ` · ${cell.evidence_ids.join("、")}` : ""}</small></td>)}</tr>)}</tbody></table></div><div className="notice"><Info />{evidenceComparison.notice}</div></Card>}
    {comparison && <><div className="comparison-grid">{comparison.products.map((product) => <Card key={product.version_id} className="comparison-product"><div className="card-title"><div><h2>{product.display_name}</h2><span>{product.version_label}</span></div><button className="icon-button" onClick={() => openProduct(product.version_id)} aria-label="查看证据"><FileSearch /></button></div><ComparisonRows product={product} /></Card>)}</div><div className="notice warning"><CircleAlert size={18} />{comparison.notice}</div><Card className="codex-card"><div><div className="card-title"><h2><Sparkles size={21} />AI 差异解读草稿</h2><StatusBadge tone="neutral">仅限两个产品</StatusBadge></div><p>完整白名单预览和逐次确认仍保留；AI 草稿不会改变事实状态。</p></div><button className="button secondary" onClick={() => void makePreview()} disabled={busy}><Bot size={18} />生成外发预览</button></Card></>}
    {previewSelection && <Card className="preview"><div className="card-title"><h2>主动选择外发证据</h2><StatusBadge tone="warning">{selectedEvidence.length}/12 段</StatusBadge></div><div className="notice warning"><CircleAlert size={18} />{previewSelection.message} 系统不会静默截断关键上下文。</div><div className="evidence-options">{previewSelection.evidence_options.map((item) => <label key={item.evidenceId}><input type="checkbox" checked={selectedEvidence.includes(item.evidenceId)} disabled={!selectedEvidence.includes(item.evidenceId) && selectedEvidence.length >= 12} onChange={(event) => setSelectedEvidence((current) => event.target.checked ? [...current, item.evidenceId] : current.filter((id) => id !== item.evidenceId))} /><div><strong>{item.product} · {fieldLabels[item.field] ?? item.field}</strong><small>{item.evidenceId} · {item.authority}</small><p>{item.text}</p></div></label>)}</div><div className="form-actions"><button className="button primary" disabled={!selectedEvidence.length || busy} onClick={() => void makePreview(selectedEvidence)}>使用所选证据生成完整预览</button></div></Card>}
    {preview && <Card className="preview"><div className="card-title"><h2>Codex 白名单外发预览</h2><StatusBadge tone="warning">{preview.excerpt_count} 段 / {preview.excerpt_characters} 字</StatusBadge></div>{preview.warnings.map((warning) => <div className="notice warning" key={warning}><CircleAlert size={17} />{warning}</div>)}<pre>{JSON.stringify(preview.payload, null, 2)}</pre>{previewUsed && <p className="notice">本次预览已调用，不会自动重试。若调用未完成，请先核对用量和记录，再主动生成新预览。</p>}<label className="confirm"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} />我已逐项查看本次完整预览，并主动确认只发送以上内容</label><div className="form-actions"><button className="button primary" disabled={!confirmed || busy || previewUsed} onClick={() => void run()}><Sparkles size={18} />确认并调用 Codex</button>{busy && <button className="button secondary" onClick={() => void policyLens.cancelCodex()}>取消运行</button>}</div></Card>}
    {analysis && <Card className="analysis"><div className="card-title"><h2><Bot size={21} />AI 草稿</h2><StatusBadge tone={analysis.status === "DRAFT" ? "warning" : analysis.status === "ACCEPTED_AS_NOTE" ? "success" : "neutral"}>{analysis.status}</StatusBadge></div><p className="analysis-summary">{analysis.result.summary}</p><h3>关键差异</h3>{analysis.result.differences.map((item) => <div className="analysis-item" key={item.title}><strong>{item.title}</strong><p>{item.explanation}</p><small>{item.evidence_ids.join("、") || "未引用具体证据"}</small></div>)}<div className="analysis-columns"><div><h3>未知项</h3><ul>{analysis.result.unknowns.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h3>风险</h3><ul>{analysis.result.risks.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h3>人工核验问题</h3><ul>{analysis.result.questions_for_human_review.map((item) => <li key={item}>{item}</li>)}</ul></div></div><div className="notice"><ShieldCheck size={18} />AI 结果未改变任何事实的 VerificationStatus。</div>{analysis.status === "DRAFT" && <div className="form-actions"><button className="button secondary" onClick={() => void updateStatus("REJECTED")}>拒绝草稿</button><button className="button primary" onClick={() => void updateStatus("ACCEPTED_AS_NOTE")}>仅接受为笔记</button></div>}</Card>}
  </>;
}

export function ComparisonRows({ product }: { product: ProductDetail }) {
  return <div className="comparison-rows"><KeyRow label="标准年费率" value={money(String(product.premium_rate?.amount ?? ""), String(product.premium_rate?.currency ?? product.currency))} /><KeyRow label="续保模式" value={String(product.renewal_terms?.renewal_mode ?? "UNKNOWN")} /><KeyRow label="保证续保期间" value={`${String(product.renewal_terms?.guarantee_period_years ?? "未知")} 年`} /><KeyRow label="最高续保年龄" value={`${String(product.renewal_terms?.maximum_renewal_age ?? "未知")} 岁`} /><KeyRow label="调费范围" value={String(product.rate_adjustment_rule?.scope ?? "UNKNOWN")} /><KeyRow label="证据字段" value={`${product.facts.filter((item) => item.verification_status === "VERIFIED").length} / ${product.facts.length} 已核验`} /></div>;
}
